theme: jekyll-theme-minimal
title: Yuichi Kono Portfolio<br><br><img src="T0HTW2RH7-U017Q26GRLH-efd1dac535e4-512.jpeg" width="250px" height="250px">
description: 河野雄一のポートフォリオ<br>
  1994.1.20 / N高等学校1年 / 事務職 / SES / Ruby / Node.js