theme: jekyll-theme-minimal
title: Yuichi Kono Portfolio<br><br><img src="T0HTW2RH7-U017Q26GRLH-efd1dac535e4-512.jpeg" width="250px" height="250px">
description: 河野雄一のポートフォリオ<br> 1994.1.20 / 事務職 / Ruby / Node.js (書き込み中)
